### ISSUE TITLE
Investigate volume correction work

### ISSUE THREAD

**Issue by fluidnumericsJoe** [FluidNumerics/FEOTS#10]

**Comment by fluidnumericsguy** [comment]
:octocat: :outbox_tray: :octopus:

**Comment by fluidnumericsJoe** [comment]
Volume correction work will involve

Uncomment volume correction terms in the forward step routines in POP_FEOTS_Class.F90

Compile with -DVOLUME_CORRECTION CPP flag enabled

Test run with a small set of transport operators and determine if methodology is stable

**Comment by fluidnumericsJoe** [comment]
In this discovery project, it was found that

* Volume correction term is already calculated
* Volume correction can be enabled with CPP Flag
* To move forward with this feature development, testing of the current implementation is needed. We can begin an implement-test-revise cycle for bringing this feature online.

Follow up issues will be needed.
