### ISSUE TITLE
Bug found in POP_Stencil_Class.f90

### ISSUE THREAD

**Issue by JiaxuZ** [FluidNumerics/FEOTS#6]
The subroutine `Build_Stencil` of `POP_Stencil_Class.f90` needs to add an elseif of 
`ELSEIF( stencilFlag == LaxWendroff27 .AND. flavor == LateralPlusCorners )THEN`
somewhere around Line 338.
This is needed when running `RegionalExtraction` for the `LaxWendroff27` stencil.
I guess this should be identical to `( stencilFlag == LaxWendroff .AND. flavor == LateralPlusCorners )`?

**Comment by fluidnumericsJoe** [comment]
I've pushed up changes that resolve this issue.
